### PR TITLE
Add wholeBodyDynamics and its related devices

### PR DESCRIPTION
**Pull request by HosameldinMohamed**
This PR adds to the `master` branch the following YARP devices:

- genericSensorClient.
- virtualAnalogClient.
- virtualAnalogRemapper.
- wholeBodyDynamics.

Related issue #43

### CODE REVIEW

**Comment by prashanthr05** [comment]
cc @HosameldinMohamed would you like to address this comment? https://github.com/robotology/whole-body-estimators/issues/43#issuecomment-597572408

**Comment by HosameldinMohamed** [comment]
> cc @HosameldinMohamed would you like to address this comment? #43 (comment)

I am not sure if we should put `set VARS_PREFIX` as for example in `iDynTree`.

https://github.com/robotology/idyntree/blob/685c0803fda91e5f8046efcd55fba3bcdc9f6907/CMakeLists.txt#L24

Because we don't use `find_package(wholeBodyEstimators)`, right?

**Comment by traversaro** [comment]
> 
> 
> > cc @HosameldinMohamed would you like to address this comment? #43 (comment)
> 
> I am not sure if we should put `set VARS_PREFIX` as for example in `iDynTree`.
> 
> https://github.com/robotology/idyntree/blob/685c0803fda91e5f8046efcd55fba3bcdc9f6907/CMakeLists.txt#L24
> 
> Because we don't use `find_package(wholeBodyEstimators)`, right?
> 
> CC @traversaro

Sorry, I am not sure what you are asking. iDynTree uses an old way of setting the version, the new one used by  this project (the version variable  in the project CMake function) is much better.

**Comment by HosameldinMohamed** [comment]
> Sorry, I am not sure what you are asking. iDynTree uses an old way of setting the version, the new one used by this project (the version variable in the project CMake function) is much better.

Ah okay, thanks, you just clarified it. I thought the different way of setting the version has a different result.

**Pull request merged**
