### PR TITLE
Implement vectors commection and use it for streaming netExternalWrenches

### PR DESCRIPTION
**Pull request by GiulioRomualdi**
This will avoid to use the bottle to stream the data.

### CODE REVIEW

**Review by traversaro — APPROVED** [review]

**Review by S-Dafarra — APPROVED** [review]

**Comment by traversaro** [comment]
@HosameldinMohamed can we merge?

**Comment by HosameldinMohamed** [comment]
> @HosameldinMohamed can we merge?

Sure!

**Comment by traversaro** [comment]
Thanks!

**Comment by HosameldinMohamed** [comment]
I updated the changelog https://github.com/robotology/whole-body-estimators/commit/92925137a42b67ff8681013044d0ccf66d20f743

**Comment by HosameldinMohamed** [comment]
Included in release https://github.com/robotology/whole-body-estimators/releases/tag/v0.9.0

**Pull request merged**
