### PR TITLE
Update WBD launch files

### LINKED ISSUE #169: Wholebodydynamics not running with iCubGazebov2_5 and iCubGazeboV3 models after update to YARP 3.8
I have tried to use `iCubGazeboV2_5` and `iCubGazeboV3` models in Gazebo and I wanted to also run `wholebodydynamics`.

I have loaded the model in Gazebo and run:

```
YARP_ROBOT_NAME=iCubGazeboV3 yarprobotinterface --config launch-wholebodydynamics.xml
```

(same for V2_5 but with a different `YARP_ROBOT_NAME`)

and I have got the following error messages:

<details>

```
[ERROR] GenericSensorClient::open() error could not connect to /icubSim/inertial
[ERROR] |yarp.dev.PolyDriver|inertial| Driver <genericSensorClient> was found but could not open
[WARNING] Cannot open device inertial
[WARNING] Cannot open device inertial
[WARNING] |yarp.device.analogsensorclient| The 'inertial' device is deprecated in favour of 'multipleanalogsensorsclient'
[WARNING] |yarp.device.analogsensorclient| The old device is no longer supported, and it will be deprecated in YARP 3.7 and removed in YARP 4.
[WARNING] |yarp.device.analogsensorclient| Please update your scripts.
[ERROR] |yarp.device.analogsensorclient| AnalogSensorClient::open() error could not connect to /icubSim/left_arm/analog:o
[ERROR] |yarp.dev.PolyDriver|left_upper_arm_strain| Driver <analogsensorclient> was found but could not open
[WARNING] Cannot open device left_upper_arm_strain
[WARNING] Cannot open device left_upper_arm_strain
[WARNING] |yarp.device.analogsensorclient| The 'inertial' device is deprecated in favour of 'multipleanalogsensorsclient'
[WARNING] |yarp.device.analogsensorclient| The old device is no longer supported, and it will be deprecated in YARP 3.7 and removed in YARP 4.
[WARNING] |yarp.device.analogsensorclient| Please update your scripts.
[ERROR] |yarp.device.analogsensorclient| AnalogSensorClient::open() error could not connect to /icubSim/right_arm/analog:o
[ERROR] |yarp.dev.PolyDriver|right_upper_arm_strain| Driver <analogsensorclient> was found but could not open
[WARNING] Cannot open device right_upper_arm_strain
[WARNING] Cannot open device right_upper_arm_strain
[WARNING] |yarp.device.analogsensorclient| The 'inertial' device is deprecated in favour of 'multipleanalogsensorsclient'
[WARNING] |yarp.device.analogsensorclient| The old device is no longer supported, and it will be deprecated in YARP 3.7 and removed in YARP 4.
[WARNING] |yarp.device.analogsensorclient| Please update your scripts.
[ERROR] |yarp.device.analogsensorclient| AnalogSensorClient::open() error could not connect to /icubSim/left_foot_front/analog:o
[ERROR] |yarp.dev.PolyDriver|left_lower_leg_front_strain| Driver <analogsensorclient> was found but could not open
[WARNING] Cannot open device left_lower_leg_front_strain
[WARNING] Cannot open device left_lower_leg_front_strain
[WARNING] |yarp.device.analogsensorclient| The 'inertial' device is deprecated in favour of 'multipleanalogsensorsclient'
[WARNING] |yarp.device.analogsensorclient| The old device is no longer supported, and it will be deprecated in YARP 3.7 and removed in YARP 4.
[WARNING] |yarp.device.analogsensorclient| Please update your scripts.
[ERROR] |yarp.device.analogsensorclient| AnalogSensorClient::open() error could not connect to /icubSim/left_foot_rear/analog:o
[ERROR] |yarp.dev.PolyDriver|left_lower_leg_rear_strain| Driver <analogsensorclient> was found but could not open
[WARNING] Cannot open device left_lower_leg_rear_strain
[WARNING] Cannot open device left_lower_leg_rear_strain
[WARNING] |yarp.device.analogsensorclient| The 'inertial' device is deprecated in favour of 'multipleanalogsensorsclient'
[WARNING] |yarp.device.analogsensorclient| The old device is no longer supported, and it will be deprecated in YARP 3.7 and removed in YARP 4.
[WARNING] |yarp.device.analogsensorclient| Please update your scripts.
[ERROR] |yarp.device.analogsensorclient| AnalogSensorClient::open() error could not connect to /icubSim/left_leg/analog:o
[ERROR] |yarp.dev.PolyDriver|left_upper_leg_strain| Driver <analogsensorclient> was found but could not open
[WARNING] Cannot open device left_upper_leg_strain
[WARNING] Cannot open device left_upper_leg_strain
[WARNING] |yarp.device.analogsensorclient| The 'inertial' device is deprecated in favour of 'multipleanalogsensorsclient'
[WARNING] |yarp.device.analogsensorclient| The old device is no longer supported, and it will be deprecated in YARP 3.7 and removed in YARP 4.
[WARNING] |yarp.device.analogsensorclient| Please update your scripts.
[ERROR] |yarp.device.analogsensorclient| AnalogSensorClient::open() error could not connect to /icubSim/right_foot_front/analog:o
[ERROR] |yarp.dev.PolyDriver|right_lower_leg_front_strain| Driver <analogsensorclient> was found but could not open
[WARNING] Cannot open device right_lower_leg_front_strain
[WARNING] Cannot open device right_lower_leg_front_strain
[WARNING] |yarp.device.analogsensorclient| The 'inertial' device is deprecated in favour of 'multipleanalogsensorsclient'
[WARNING] |yarp.device.analogsensorclient| The old device is no longer supported, and it will be deprecated in YARP 3.7 and removed in YARP 4.
[WARNING] |yarp.device.analogsensorclient| Please update your scripts.
[ERROR] |yarp.device.analogsensorclient| AnalogSensorClient::open() error could not connect to /icubSim/right_foot_rear/analog:o
[ERROR] |yarp.dev.PolyDriver|right_lower_leg_rear_strain| Driver <analogsensorclient> was found but could not open
[WARNING] Cannot open device right_lower_leg_rear_strain
[WARNING] Cannot open device right_lower_leg_rear_strain
[WARNING] |yarp.device.analogsensorclient| The 'inertial' device is deprecated in favour of 'multipleanalogsensorsclient'
[WARNING] |yarp.device.analogsensorclient| The old device is no longer supported, and it will be deprecated in YARP 3.7 and removed in YARP 4.
[WARNING] |yarp.device.analogsensorclient| Please update your scripts.
[ERROR] |yarp.device.analogsensorclient| AnalogSensorClient::open() error could not connect to /icubSim/right_leg/analog:o
[ERROR] |yarp.dev.PolyDriver|right_upper_leg_strain| Driver <analogsensorclient> was found but could not open
[WARNING] Cannot open device right_upper_leg_strain
[WARNING] Cannot open device right_upper_leg_strain
[WARNING] subModel no  4  has the maximum number of variables (6). The frame  l_lower_leg  will not be added to it.
[WARNING] subModel no  1  has the maximum number of variables (6). The frame  r_lower_leg  will not be added to it.
[WARNING] There was some problem opening one or more devices. Please check the log and your configuration
[ERROR] One or more devices failed opening... see previous log messages for more info
[ERROR] Error in startup phase... see previous messages for more info
[WARNING] Interrupt # 1 # received.
[ERROR] wholebodydynamics is neither a wrapper nor a multiplewrapper, therefore it cannot have detach actions
[ERROR] Cannot run detach action on device wholebodydynamics
[WARNING] There was some problem running actions for shutdown phase . Please check the log and your configuration
[ERROR] Error in shutdown phase... see previous messages for more info
```

</details>

Here the output of `yarp name list`:

<details>

```
registration name /clock ip 10.240.2.15 port 10002 type tcp
registration name /clock/rpc ip 10.240.2.15 port 10003 type tcp
registration name /gabri ip 172.17.0.1 port 10000 type tcp
registration name /icubSim/head/command:i ip 10.240.2.15 port 10033 type tcp
registration name /icubSim/head/inertials/measures:o ip 10.240.2.15 port 10092 type tcp
registration name /icubSim/head/inertials/rpc:o ip 10.240.2.15 port 10093 type tcp
registration name /icubSim/head/rpc:i ip 10.240.2.15 port 10032 type tcp
registration name /icubSim/head/state:o ip 10.240.2.15 port 10034 type tcp
registration name /icubSim/head/stateExt:o ip 10.240.2.15 port 10035 type tcp
registration name /icubSim/left_arm/command:i ip 10.240.2.15 port 10021 type tcp
registration name /icubSim/left_arm/measures:o ip 10.240.2.15 port 10084 type tcp
registration name /icubSim/left_arm/rpc:i ip 10.240.2.15 port 10020 type tcp
registration name /icubSim/left_arm/rpc:o ip 10.240.2.15 port 10085 type tcp
registration name /icubSim/left_arm/state:o ip 10.240.2.15 port 10022 type tcp
registration name /icubSim/left_arm/stateExt:o ip 10.240.2.15 port 10023 type tcp
registration name /icubSim/left_foot_heel_tiptoe/measures:o ip 10.240.2.15 port 10080 type tcp
registration name /icubSim/left_foot_heel_tiptoe/rpc:o ip 10.240.2.15 port 10081 type tcp
registration name /icubSim/left_leg/command:i ip 10.240.2.15 port 10013 type tcp
registration name /icubSim/left_leg/rpc:i ip 10.240.2.15 port 10012 type tcp
registration name /icubSim/left_leg/state:o ip 10.240.2.15 port 10014 type tcp
registration name /icubSim/left_leg/stateExt:o ip 10.240.2.15 port 10015 type tcp
registration name /icubSim/left_leg_hip/measures:o ip 10.240.2.15 port 10090 type tcp
registration name /icubSim/left_leg_hip/rpc:o ip 10.240.2.15 port 10091 type tcp
registration name /icubSim/right_arm/command:i ip 10.240.2.15 port 10017 type tcp
registration name /icubSim/right_arm/measures:o ip 10.240.2.15 port 10086 type tcp
registration name /icubSim/right_arm/rpc:i ip 10.240.2.15 port 10016 type tcp
registration name /icubSim/right_arm/rpc:o ip 10.240.2.15 port 10087 type tcp
registration name /icubSim/right_arm/state:o ip 10.240.2.15 port 10018 type tcp
registration name /icubSim/right_arm/stateExt:o ip 10.240.2.15 port 10019 type tcp
registration name /icubSim/right_foot_heel_tiptoe/measures:o ip 10.240.2.15 port 10082 type tcp
registration name /icubSim/right_foot_heel_tiptoe/rpc:o ip 10.240.2.15 port 10083 type tcp
registration name /icubSim/right_leg/command:i ip 10.240.2.15 port 10025 type tcp
registration name /icubSim/right_leg/rpc:i ip 10.240.2.15 port 10024 type tcp
registration name /icubSim/right_leg/state:o ip 10.240.2.15 port 10026 type tcp
registration name /icubSim/right_leg/stateExt:o ip 10.240.2.15 port 10027 type tcp
registration name /icubSim/right_leg_hip/measures:o ip 10.240.2.15 port 10088 type tcp
registration name /icubSim/right_leg_hip/rpc:o ip 10.240.2.15 port 10089 type tcp
registration name /icubSim/torso/command:i ip 10.240.2.15 port 10029 type tcp
registration name /icubSim/torso/rpc:i ip 10.240.2.15 port 10028 type tcp
registration name /icubSim/torso/state:o ip 10.240.2.15 port 10030 type tcp
registration name /icubSim/torso/stateExt:o ip 10.240.2.15 port 10031 type tcp
registration name /wholeBodyDynamics/left_arm/cartesianEndEffectorWrench:o ip 10.240.2.15 port 10072 type tcp
registration name /wholeBodyDynamics/left_foot/cartesianEndEffectorWrench:o ip 10.240.2.15 port 10074 type tcp
registration name /wholeBodyDynamics/left_foot_front/cartesianEndEffectorWrench:o ip 10.240.2.15 port 10108 type tcp
registration name /wholeBodyDynamics/left_foot_rear/cartesianEndEffectorWrench:o ip 10.240.2.15 port 10109 type tcp
registration name /wholeBodyDynamics/left_lower_leg/cartesianEndEffectorWrench:o ip 10.240.2.15 port 10106 type tcp
registration name /wholeBodyDynamics/left_upper_leg/cartesianEndEffectorWrench:o ip 10.240.2.15 port 10104 type tcp
registration name /wholeBodyDynamics/right_arm/cartesianEndEffectorWrench:o ip 10.240.2.15 port 10073 type tcp
registration name /wholeBodyDynamics/right_foot/cartesianEndEffectorWrench:o ip 10.240.2.15 port 10075 type tcp
registration name /wholeBodyDynamics/right_foot_front/cartesianEndEffectorWrench:o ip 10.240.2.15 port 10110 type tcp
registration name /wholeBodyDynamics/right_foot_rear/cartesianEndEffectorWrench:o ip 10.240.2.15 port 10111 type tcp
registration name /wholeBodyDynamics/right_lower_leg/cartesianEndEffectorWrench:o ip 10.240.2.15 port 10107 type tcp
registration name /wholeBodyDynamics/right_upper_leg/cartesianEndEffectorWrench:o ip 10.240.2.15 port 10105 type tcp
registration name fallback ip 224.2.1.1 port 10000 type mcast


```

</details>

Here the complete logger [wbd_log.txt](https://github.com/robotology/whole-body-estimators/files/11156732/wbd_log.txt)

cc @traversaro

### PR DESCRIPTION
**Pull request by HosameldinMohamed**
This PR updates the launch files for `wholeBodyDynamics` to align them with the latest `robots-configuration` and `icub-models` settings. The modifications include:

- F/T sensors are interfaced as MAS instead of analogSensor devices.
- IMU is interfaced as MAS instead of GenericSensor device.
- IMU frame updated.
- Fixed including the estimator files.

I tested the launch file `launch-wholebodydynamics-icub-six-fts-sim.xml` with `iCubGazebo2_5`, and `launch-wholebodydynamics-icub3-sim.xml` with `iCubGazeboV3`.

For the others, that are supposed to be with real robots, I haven't tested them.

This may fix #169

### CODE REVIEW

**Comment by HosameldinMohamed** [comment]
I'm not sure if we should maintain these files `launch-wholebodydynamics-icubheidelberg01.xml`, `wholebodydynamics-icubheidelberg01-external.xml` and `wholebodydynamics-icubheidelberg01-robot.xml` that point to a specific robot, especially that I don't see `icubheidelberg01` anymore in the latest [`robots-configurations`](https://github.com/robotology/robots-configuration/tree/v2.5.0).

**Review by traversaro — APPROVED** [review]
Thanks a lot!

**Comment by traversaro** [comment]
> I'm not sure if we should maintain these files `launch-wholebodydynamics-icubheidelberg01.xml`, `wholebodydynamics-icubheidelberg01-external.xml` and `wholebodydynamics-icubheidelberg01-robot.xml` that point to a specific robot, especially that I don't see `icubheidelberg01` anymore in the latest [`robots-configurations`](https://github.com/robotology/robots-configuration/tree/v2.5.0).

Yes, I think we can remove them. Those were "special" as that robot only had legs.

**Comment by HosameldinMohamed** [comment]
> I tested the launch file `launch-wholebodydynamics-icub-six-fts-sim.xml` with `iCubGazebo2_5`, and `launch-wholebodydynamics-icub3-sim.xml` with `iCubGazeboV3`.

WBD runs with no errors, I haven't really checked what it's estimating!

**Comment by HosameldinMohamed** [comment]
Also, the files `wholebodydynamics-icub-eth-six-fts.xml` and `wholebodydynamics-icub-external-and-can-six-fts.xml` seem identical. I'm not sure why they are here, and why they are called `can` and `eth`?

**Comment by traversaro** [comment]
> Also, the files `wholebodydynamics-icub-eth-six-fts.xml` and `wholebodydynamics-icub-external-and-can-six-fts.xml` seem identical. I'm not sure why they are here, and why they are called `can` and `eth`?

The difference is in the `<action phase="startup" level="15" type="attach">` tag. For ETH there are not special virtual analog sensors to attach, while for `can` and `external` there are separate device for virtual analog sensors:
~~~
                <elem name="left_leg_vsens">left_leg_virtual_strain</elem>
                <elem name="right_leg_vsens">right_leg_virtual_strain</elem>
                <elem name="torso_vsens">torso_virtual_strain</elem>
                <elem name="right_arm_vsens">right_arm_virtual_strain</elem>
                <elem name="left_arm_vsens">left_arm_virtual_strain</elem>
~~~

Why is this happening? We need a bit of history here. 

The first versions of the iCubs used internally a set of CAN bus for communications with their internal control and sensor embedded boards. This had limitation of the amount of data that could be sent, so iCub 2.* was developed with an internal ETH (i.e. ethernet) bus that connected it with its internal control and sensor boards. This meant that `yarprobotinterface` of  ETH and CAN robots used different devices to communicate with controlboard, i.e. [`canBusMotionControl`](https://github.com/robotology/icub-main/tree/v2.2.1/src/libraries/icubmod/canBusMotionControl) for `CAN`  robots and [`embObjMotionControl`](https://github.com/robotology/icub-main/tree/v2.2.1/src/libraries/icubmod/embObjMotionControl) for ETH robots.

However, the main difference for us is how joint torques estimates computed by WBD are sent down to the control boards for closing the torque loop. This measure is exposed to control boards via the `updateVirtualAnalogSensorMeasure` method contained in the [`yarp::dev::IVirtualAnalogSensor`](https://www.yarp.it/git-master/classyarp_1_1dev_1_1IVirtualAnalogSensor.html) interface, that WBD calls inside the publishTorques method (https://github.com/robotology/whole-body-estimators/blob/fb0e29580ab2524d86ce910ad2af37eea6e4f3d9/devices/wholeBodyDynamics/WholeBodyDynamicsDevice.cpp#L2764). 

In the case of CAN robots, there was a dedicated device called [`canBusVirtualAnalogSensor`](https://github.com/robotology/icub-main/tree/v2.2.1/src/libraries/icubmod/canBusVirtualAnalogSensor) that exposed the `updateVirtualAnalogSensorMeasure` method, see for example the devices instantiated in https://github.com/robotology/robots-configuration/blob/85237b0397c206588031289298e268c7e229e893/iCubGenova03/icub_all.xml#L39 (`iCubGenova03` is a CAN robot).

Instead, for ETH robots the `updateVirtualAnalogSensorMeasure` method was directly exposed by the `embObjMotionControl` device used also for motor control, see https://github.com/robotology/icub-main/blob/v2.2.1/src/libraries/icubmod/embObjMotionControl/embObjMotionControl.h . So, for ETH robots you can connect to the `embObjMotionControl` devices for both reading the encoders and updating the estimated torques, while whe CAN robot you need to connect to `canBusMotionControl` to read encoders and to `canBusVirtualAnalogSensor` to update the torques estimated.

What I just described applies to when the `wholebodydynamics` device runs inside the main `yarprobotinterface`  of the robot. But what happens instead when  `wholebodydynamics` is launched externally, i.e. with an external `yarprobotinterface`  ? In that case, the situation is similar to `CAN`  robots, as there are two separate `nws`/`remapper`/`nwc` triples for reading encoders and for set measured torques. `controlBoard_yarp_nws`/`controlboardremapper`/`remote_controlboard` are the devices to read encoders, while `virtualAnalogServer`/`virtualAnalogRemapper`/`virtualAnalogClient` are the devices to update torque estimates. For this reason, when the wbd is launched externally, we need two different devices, one type to read encoders (`remote_controlboard`) and one to update the torque estimates (`virtualAnalogClient`), so this is the reason why the external case and the CAN case can be dealt with the same configuration file, while the eth with a different configuration file.

Sorry for the wall of text, if you got lost with all the names please let me know and we can discuss in person.

**Comment by HosameldinMohamed** [comment]
Thanks a lot for the clear explanation. Got it now!
I was also wondering about the virtual torque devices, now I understand!

**Pull request merged**
