### PR TITLE
Fixed the configuration files to run wholeBodyDynamics with iCubGazeboV3

### PR DESCRIPTION
**Pull request by S-Dafarra**
Fixes https://github.com/robotology/whole-body-estimators/issues/98

### CODE REVIEW

**Review by traversaro — APPROVED** [review]
Ok, but eventually I think we should move it just in robots-configurations together with all other robot-specific conf files.

**Comment by S-Dafarra** [comment]
> Ok, but eventually I think we should move it just in robots-configurations together with all other robot-specific conf files.

I don't think we have Gazebo related configuration files in there :thinking:

**Comment by traversaro** [comment]
> 
> 
> > Ok, but eventually I think we should move it just in robots-configurations together with all other robot-specific conf files.
> 
> I don't think we have Gazebo related configuration files in there 🤔

You are right, I was confused!

**Review by prashanthr05 — APPROVED** [review]
Thanks @S-Dafarra ! Could you just add the relevant PR link in the changelog ?

**Comment by S-Dafarra** [comment]
> Thanks @S-Dafarra ! Could you just add the relevant PR link in the changelog ?

Done in https://github.com/robotology/whole-body-estimators/pull/107/commits/66a6801faf5b8bec9f57dd0d3615dedef7bd1c6d

**Comment by prashanthr05** [comment]
Merged, thanks!

**Pull request merged**
