### PR TITLE
[WBD] update `calibStandingWithJetsiRonCubMk1` for iRonCub-Mk1_1

### PR DESCRIPTION
**Pull request by HosameldinMohamed**
Related PR #113 which was done for `iRonCub-Mk1`. We modify the `RPC` command to be compatible with `iRonCub-Mk1_1`.

### CODE REVIEW

**Comment by HosameldinMohamed** [comment]
It's a simple PR but to be sure I am not forgetting anything!

**Comment by prashanthr05** [comment]
I believe you must also commit the autogenerated IDL files?

**Comment by HosameldinMohamed** [comment]
> I believe you must also commit the autogenerated IDL files?

I suppose not @prashanthr05. After #131 we no longer save the autogenerated files.

**Comment by traversaro** [comment]
Why remove the old method `calibStandingWithJetsiRonCubMk1` ?

**Comment by HosameldinMohamed** [comment]
> Why remove the old method `calibStandingWithJetsiRonCubMk1` ?

I wanted to avoid duplicating the code. Because the only change between the methods is in the idle thrust of the arms jets.

Also, I don't think we will be using `iRonCub-Mk1` again, unless we really have to.
But now that you raised this point. It's better to double-check with the team to have a definitive answer.

**Comment by traversaro** [comment]
> > Why remove the old method `calibStandingWithJetsiRonCubMk1` ?
> 
> I wanted to avoid duplicating the code. Because the only change between the methods is in the idle thrust of the arms jets.

We could have an helper method that just takes idle thrust and arm jets as parameters, and then you call that one on the different `calibtStandingWithJets***` methods?

**Comment by HosameldinMohamed** [comment]
> Are you sure that it is ok to have a breaking change? If you prefer to still have `calibStandingWithJetsiRonCubMk1` you can still keep this method and just call `calibStandingWithJetsiRonCub("mk1")` in its implementation, but this is up do you.

@traversaro I see, Which of the two below did you mean?

- Did you mean the user should be able to call both `calibStandingWithJetsiRonCub` (passing a parameter) and `calibStandingWithJetsiRonCubMk1` (with a deprecation warning maybe?).

- Or did you mean the user should be able to call `calibStandingWithJetsiRonCubMk1` and `calibStandingWithJetsiRonCubMk1_1`, while both internally implement the same method?

Just to understand the better practice. But in this particular case, only the iRonCub team are using it. So I think it should be fine to add a breaking change.

**Review by traversaro — APPROVED** [review]

**Comment by HosameldinMohamed** [comment]
Thanks!

**Comment by traversaro** [comment]
Yes I was referring to both cases you were referring to.

**Comment by HosameldinMohamed** [comment]
> Yes I was referring to both cases you were referring to.

Ok. I agree that in general this kind of change can be harmful but in this case it should be ok. I added some documentation of the RPC commands #137.

**Pull request merged**
