### PR TITLE
Fix CMake variable replacement

### LINKED ISSUE #78: Wrong CMake variable replacement
In the CMake files of the yarprobotinterface's xml file I can see that few variables should be replaced, such as:

https://github.com/robotology/whole-body-estimators/blob/38dc6a269f1b0bce09f31d8ae9c4ca3602e8e46b/devices/wholeBodyDynamics/app/CMakeLists.txt#L32-L34

However, the xml files have a wrong variable and it is not actually substituted by `configure_file`. In fact, the following

https://github.com/robotology/whole-body-estimators/blob/38dc6a269f1b0bce09f31d8ae9c4ca3602e8e46b/devices/wholeBodyDynamics/app/launch-wholebodydynamics-icub-six-fts-sim.xml#L4

should instead contain `@WBD_YARP_ROBOT_NAME@`.

cc @prashanthr05 @HosameldinMohamed @traversaro

### PR DESCRIPTION
**Pull request by diegoferigo**
Closes #78 

cc @prashanthr05 @traversaro

### CODE REVIEW

**Comment by prashanthr05** [comment]
Merged, thank you @diegoferigo !

**Comment by diegoferigo** [comment]
@prashanthr05 can you please also merge `master` into `devel`?

**Comment by prashanthr05** [comment]
Done! Sorry if it took some time.

**Comment by diegoferigo** [comment]
No prob, thanks @prashanthr05!!

**Pull request merged**
