### PR TITLE
Fix YARP deprecations

### LINKED ISSUE #150: Cleanup YARP deprecations
The deprecated YARP method asDouble is still used in the whole-body-estimators, see for example https://github.com/robotology/whole-body-estimators/blob/353985f3997e89dbc6744105077765457e2e0227/devices/baseEstimatorV1/src/configureEstimator.cpp#L35. The code will break once https://github.com/robotology/yarp/pull/2833 will be merged.

### PR DESCRIPTION
**Pull request by prashanthr05**
Closes #150

### CODE REVIEW

**Review by traversaro — APPROVED** [review]

**Comment by traversaro** [comment]
Thanks @prashanthr05 !

**Review by HosameldinMohamed — APPROVED** [review]

**Comment by HosameldinMohamed** [comment]
Thanks, @prashanthr05. Does it make sense to update the changelog?

**Comment by prashanthr05** [comment]
> Thanks, @prashanthr05. Does it make sense to update the changelog?

Done. :)

**Comment by traversaro** [comment]
Thansk a lot @HosameldinMohamed @prashanthr05 !

**Pull request merged**
