### PR TITLE
Introduce MAS Read in whole body estimator 

### PR DESCRIPTION
**Pull request by CarlottaSartore**
C.C. @traversaro

### CODE REVIEW

**Review by traversaro — APPROVED** [review]
Can you add a line in the Changelog?

**Comment by isorrentino** [comment]
Can we merge this PR? Before merging I think it is necessary to rebase this branch on master.
Maybe also the line in the Changelog is still missing.

cc @prashanthr05 @traversaro @CarlottaSartore

**Comment by isorrentino** [comment]
CHANGELOG updated!

**Comment by CarlottaSartore** [comment]
Thanks @isorrentino, from my point of view this PR can be merged, we tested also in Rimini and everything went fine !

**Comment by isorrentino** [comment]
cc @HosameldinMohamed

**Comment by traversaro** [comment]
Sorry @HosameldinMohamed, did you had a chance of checking this PR?

**Comment by HosameldinMohamed** [comment]
> Sorry @HosameldinMohamed, did you had a chance of checking this PR?

Not yet, sorry for the delay. Doing it now..

**Comment by traversaro** [comment]
Thanks @HosameldinMohamed !

**Pull request merged**
