### PR TITLE
Merge devel in master

### PR DESCRIPTION
**Pull request by traversaro**
As master is empty, it should  not be a big problem. : )

### CODE REVIEW

**Comment by traversaro** [comment]
@prashanthr05 can we proceed on this? I think it should not impact anyone working with this repo.

**Comment by prashanthr05** [comment]
For me, it's a green flag.

As an exhaustive user of this estimator, I would like to have @GiulioRomualdi opinion on this as well.
Do you think we can merge into master or would you like something specific to be addressed before merging into master?

**Comment by traversaro** [comment]
@prashanthr05 as you are the mantainer feel free to merge, thanks!

**Comment by prashanthr05** [comment]
Merged, thanks!

**Pull request merged**
