### PR TITLE
Merge devel to master for a new release

### PR DESCRIPTION
**Pull request by prashanthr05**

### CODE REVIEW

**Comment by traversaro** [comment]
If you need to add the new feature for iCub3, we can probably add it and then do the release later, what do you think?

**Comment by prashanthr05** [comment]
> If you need to add the new feature for iCub3, we can probably add it and then do the release later, what do you think?

Agreed. I will open a PR for that.

**Comment by traversaro** [comment]
Actually I was thinking of https://github.com/robotology/whole-body-estimators/pull/88 that was already in devel, but also the iCubGazeboV3 conf files are probably ok. :D

**Review by traversaro — APPROVED** [review]

**Review by HosameldinMohamed — APPROVED** [review]

**Comment by HosameldinMohamed** [comment]
Merged. Thanks!

**Comment by HosameldinMohamed** [comment]
should the new release be `v0.3.0` since the [changelog](https://github.com/robotology/whole-body-estimators/blob/master/CHANGELOG.md) contains only additions and no fixes?

> ## Unreleased
> ### Added
> - Added 'startWithZeroFTSensorOffsets' option when passed starts the WBD device with zero offsets for FT sensors, bypassing the offset calibration. (See [!72](https://github.com/robotology/whole-body-estimators/pull/72)).
> - Added support for compensating temperature in Force/Torque sensors readings and for specify user offline offset. (See [!45](https://github.com/robotology/whole-body-estimators/pull/45))
> - Added `useSkinForContacts` option flag to enable/disable the usage of tactile skin sensor information for updating contact points and relevant information. (See [!88](https://github.com/robotology/whole-body-estimators/pull/88))
> - Added `wholeBodyDynamics` configuration files for `iCubGazeboV3`. (See [!90](https://github.com/robotology/whole-body-estimators/pull/90))

**Comment by traversaro** [comment]
> should the new release be v0.3.0 since the changelog contains only additions and no fixes?

I agree!

**Comment by prashanthr05** [comment]
Updated changelog for new release to v0.3.0 in https://github.com/robotology/whole-body-estimators/blob/master/CHANGELOG.md

**Pull request merged**
