### PR TITLE
Added possibility to publish net wrenches

### PR DESCRIPTION
**Pull request by S-Dafarra**

### CODE REVIEW

**Review by traversaro — APPROVED** [review]

**Comment by traversaro** [comment]
Can you mention this in the CHANGELOG?

**Comment by S-Dafarra** [comment]
> Can you mention this in the CHANGELOG?

I did it in https://github.com/robotology/whole-body-estimators/pull/111/commits/b15115a1b8c5a04a6b19275f14f089f45c0e9531

**Review by prashanthr05 — APPROVED** [review]

**Comment by prashanthr05** [comment]
Thanks @S-Dafarra. Let me know if I can proceed with the merge?

**Comment by S-Dafarra** [comment]
> Thanks @S-Dafarra. Let me know if I can proceed with the merge?

Yes, we can proceed!

**Comment by prashanthr05** [comment]
Merged, thanks!

**Pull request merged**
